[Variables]
;   Option: include a font file
;FontFace="#@#\Fonts\_.ttf"
FontFace=Noto Sans Mono

[Outlined]
StringAlign=Left
StringEffect=Border
FontEffectColor=#FontOutlineColor#
FontFace=#FontFace#
StringStyle=Bold
FontSize=20
FontColor=#FontColor#
AntiAlias=1
ClipString=1

[Outlined-Small]
StringAlign=Left
StringEffect=Border
FontEffectColor=#FontOutlineColor#
FontFace=#FontFace#
StringStyle=Bold
FontSize=16
FontColor=#FontColor#
AntiAlias=1
ClipString=1

[Outlined-Right]
StringAlign=Right
StringEffect=Border
FontEffectColor=#FontOutlineColor#
FontFace=#FontFace#
StringStyle=Bold
FontSize=20
FontColor=#FontColor#
AntiAlias=1
ClipString=1

[Outlined-Right-Small]
StringAlign=Right
StringEffect=Border
FontEffectColor=#FontOutlineColor#
FontFace=#FontFace#
StringStyle=Bold
FontSize=16
FontColor=#FontColor#
AntiAlias=1
ClipString=1

[Outlined-Centered]
StringAlign=Center
StringEffect=Border
FontFace=#FontFace#
StringStyle=Bold
FontSize=42
FontColor=#FontColor#
AntiAlias=1
ClipString=1

[Outlined-Centered-Small]
StringAlign=Center
StringEffect=Border
FontEffectColor=#FontOutlineColor#
FontFace=#FontFace#
StringStyle=Bold
FontSize=16
FontColor=#FontColor#
AntiAlias=1
ClipString=1

[Outlined-Title]
StringAlign=Left
StringEffect=Border
FontEffectColor=#FontOutlineColor#
FontFace=#FontFace#
StringStyle=Bold
FontSize=22
FontColor=#FontColor#
AntiAlias=1
ClipString=1

[Outlined-Title-Right]
StringAlign=Right
StringEffect=Border
FontEffectColor=#FontOutlineColor#
FontFace=#FontFace#
StringStyle=Bold
FontSize=22
FontColor=#FontColor#
AntiAlias=1
ClipString=1
