[Variables]

;   Link to an Online RGB Color Picker: https://rgbcolorpicker.com/

;   Colors [Red,Green,Blue] -- **Don't Include Alpha(A)**

FrameColor=180,180,180
TealColor=7,180,166
AccentColor=123,168,162
WarnRed=237,28,36
WarnOrange=241,104,35
WarnYellow=237,185,35
IconColor=255,255,255,155
GpuGreen=1,250,175
GaugeFaceColor=122,93,93,255

BarBgColor=30,30,30,0
GaugeColor=240,240,240
GaugeCoverColor=88,88,88

;FontColor=0,191,251
FontColor=210,210,210
FontOutlineColor=10,10,10
